delete from TGv1000.types where ordinal=10000;
update TGv1000.types SET name='Game Base Type',isApp=0,imageId=0,altImagePath='media/images/gameProject.png' ,ordinal=10000,comicId=null,description='null' ,parentTypeId=null,parentPrice=0,priceBump=0,ownedByUserId=null,public=0,quarantined=0,baseTypeId=null where id=1;delete from TGv1000.methods where typeId=1;delete from TGv1000.propertys where typeId=1;delete from TGv1000.events where typeId=1;delete from TGv1000.type_tags where typeId=1;
update TGv1000.types SET name='Console Base Type',isApp=0,imageId=0,altImagePath='media/images/consoleProject.png' ,ordinal=10000,comicId=null,description='null' ,parentTypeId=null,parentPrice=0,priceBump=0,ownedByUserId=null,public=0,quarantined=0,baseTypeId=null where id=2;delete from TGv1000.methods where typeId=2;delete from TGv1000.propertys where typeId=2;delete from TGv1000.events where typeId=2;delete from TGv1000.type_tags where typeId=2;
update TGv1000.types SET name='Website Base Type',isApp=0,imageId=0,altImagePath='media/images/websiteProject.png' ,ordinal=10000,comicId=null,description='null' ,parentTypeId=null,parentPrice=0,priceBump=0,ownedByUserId=null,public=0,quarantined=0,baseTypeId=null where id=3;delete from TGv1000.methods where typeId=3;delete from TGv1000.propertys where typeId=3;delete from TGv1000.events where typeId=3;delete from TGv1000.type_tags where typeId=3;
update TGv1000.types SET name='Hololens Base Type',isApp=0,imageId=0,altImagePath='media/images/hololensProject.png' ,ordinal=10000,comicId=null,description='null' ,parentTypeId=null,parentPrice=0,priceBump=0,ownedByUserId=null,public=0,quarantined=0,baseTypeId=null where id=4;delete from TGv1000.methods where typeId=4;delete from TGv1000.propertys where typeId=4;delete from TGv1000.events where typeId=4;delete from TGv1000.type_tags where typeId=4;
update TGv1000.types SET name='Map Base Type',isApp=0,imageId=0,altImagePath='media/images/mappingProject.png' ,ordinal=10000,comicId=null,description='null' ,parentTypeId=null,parentPrice=0,priceBump=0,ownedByUserId=null,public=0,quarantined=0,baseTypeId=null where id=5;delete from TGv1000.methods where typeId=5;delete from TGv1000.propertys where typeId=5;delete from TGv1000.events where typeId=5;delete from TGv1000.type_tags where typeId=5;
call TGv1000.doTag('type',1,'type');
call TGv1000.doTag('game_base_type',1,'type');
call TGv1000.doTag('type',2,'type');
call TGv1000.doTag('console_base_type',2,'type');
call TGv1000.doTag('type',3,'type');
call TGv1000.doTag('website_base_type',3,'type');
call TGv1000.doTag('type',4,'type');
call TGv1000.doTag('hololens_base_type',4,'type');
call TGv1000.doTag('type',5,'type');
call TGv1000.doTag('map_base_type',5,'type');
insert TGv1000.methods SET typeId=1,name='construct',ordinal=0,workspace='<xml xmlns="http://www.w3.org/1999/xhtml"><block type="procedures_defnoreturn"><mutation><arg name="self"></arg></mutation><field name="NAME">construct</field></block></xml>' ,imageId=0,description='',parentMethodId=0,parentPrice=0,priceBump=0,ownedByUserId=1,public=1,quarantined=0,methodTypeId=4,parameters='',id=18;
insert TGv1000.methods SET typeId=2,name='construct',ordinal=0,workspace='<xml xmlns="http://www.w3.org/1999/xhtml"><block type="procedures_defnoreturn"><mutation><arg name="self"></arg></mutation><field name="NAME">construct</field></block></xml>' ,imageId=0,description='',parentMethodId=0,parentPrice=0,priceBump=0,ownedByUserId=1,public=1,quarantined=0,methodTypeId=4,parameters='',id=19;
insert TGv1000.methods SET typeId=3,name='construct',ordinal=0,workspace='<xml xmlns="http://www.w3.org/1999/xhtml"><block type="procedures_defnoreturn"><mutation><arg name="self"></arg></mutation><field name="NAME">construct</field></block></xml>' ,imageId=0,description='',parentMethodId=0,parentPrice=0,priceBump=0,ownedByUserId=1,public=1,quarantined=0,methodTypeId=4,parameters='',id=20;
insert TGv1000.methods SET typeId=4,name='construct',ordinal=0,workspace='<xml xmlns="http://www.w3.org/1999/xhtml"><block type="procedures_defnoreturn"><mutation><arg name="self"></arg></mutation><field name="NAME">construct</field></block></xml>' ,imageId=0,description='',parentMethodId=0,parentPrice=0,priceBump=0,ownedByUserId=1,public=1,quarantined=0,methodTypeId=4,parameters='',id=21;
insert TGv1000.methods SET typeId=5,name='construct',ordinal=0,workspace='<xml xmlns="http://www.w3.org/1999/xhtml"><block type="procedures_defnoreturn"><mutation><arg name="self"></arg></mutation><field name="NAME">construct</field></block></xml>' ,imageId=0,description='',parentMethodId=0,parentPrice=0,priceBump=0,ownedByUserId=1,public=1,quarantined=0,methodTypeId=4,parameters='',id=22;
call TGv1000.doTag('method',18,'method');
call TGv1000.doTag('construct',18,'method');
call TGv1000.doTag('method',19,'method');
call TGv1000.doTag('construct',19,'method');
call TGv1000.doTag('method',20,'method');
call TGv1000.doTag('construct',20,'method');
call TGv1000.doTag('method',21,'method');
call TGv1000.doTag('construct',21,'method');
call TGv1000.doTag('method',22,'method');
call TGv1000.doTag('construct',22,'method');